apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: geemike/tasks
          env:
            - name: POSTGRES_URL
              value: 'tasks-postgres-srv'
            - name: POSTGRES_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: password
            - name: JWT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: jwt
                    key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-srv
spec:
  selector:
    app: tasks
  ports:
    - name: tasks
      protocol: TCP
      port: 3000
      targetPort: 3000
